INFO:     Will watch for changes in these directories: ['/home/prasdud/playground/python/SpeechEmotion-LSTM']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [27922] using StatReload
INFO:     Started server process [27924]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:root:WebSocket connection request received.
INFO:     127.0.0.1:36420 - "WebSocket /ws" [accepted]
INFO:root:WebSocket connection accepted.
INFO:root:Starting WebSocket handler.
INFO:src.api.utils.utils:Entering handle_websocket
INFO:src.api.utils.utils:Exiting handle_websocket
INFO:     connection open
ERROR:root:Websocket error: (<CloseCode.ABNORMAL_CLOSURE: 1006>, '')
ERROR:root:WebSocket handler error: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (<CloseCode.ABNORMAL_CLOSURE: 1006>, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 360, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
INFO:root:WebSocket handler finished.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (<CloseCode.ABNORMAL_CLOSURE: 1006>, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 360, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 364, in handle
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 149, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 146, in app
    await func(session)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 461, in app
    await dependant.call(**solved_result.values)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 23, in websocket_endpoint
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 98, in send
    raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.
INFO:     connection closed
INFO:root:WebSocket connection request received.
INFO:     127.0.0.1:36434 - "WebSocket /ws" [accepted]
INFO:root:WebSocket connection accepted.
INFO:root:Starting WebSocket handler.
INFO:src.api.utils.utils:Entering handle_websocket
INFO:src.api.utils.utils:Exiting handle_websocket
INFO:     connection open
ERROR:root:Websocket error: (1001, '')
ERROR:root:WebSocket handler error: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1001, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 360, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
INFO:root:WebSocket handler finished.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1001, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 360, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 364, in handle
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 149, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 146, in app
    await func(session)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 461, in app
    await dependant.call(**solved_result.values)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 23, in websocket_endpoint
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 98, in send
    raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.
INFO:     connection closed
INFO:root:WebSocket connection request received.
INFO:     127.0.0.1:57206 - "WebSocket /ws" [accepted]
INFO:root:WebSocket connection accepted.
INFO:root:Starting WebSocket handler.
INFO:src.api.utils.utils:Entering handle_websocket
INFO:src.api.utils.utils:Exiting handle_websocket
INFO:     connection closed
ERROR:root:Websocket error: (1006, None)
ERROR:root:WebSocket handler error: 'WebSocketProtocol' object has no attribute 'transfer_data_task'
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1006, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 338, in asgi_send
    await self.close(code, reason)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 773, in close
    await self.transfer_data_task
AttributeError: 'WebSocketProtocol' object has no attribute 'transfer_data_task'. Did you mean: 'transfer_data_exc'?
INFO:root:WebSocket handler finished.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1006, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 338, in asgi_send
    await self.close(code, reason)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 773, in close
    await self.transfer_data_task
AttributeError: 'WebSocketProtocol' object has no attribute 'transfer_data_task'. Did you mean: 'transfer_data_exc'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 364, in handle
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 149, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 146, in app
    await func(session)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 461, in app
    await dependant.call(**solved_result.values)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 23, in websocket_endpoint
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 98, in send
    raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.
INFO:root:WebSocket connection request received.
INFO:     127.0.0.1:57216 - "WebSocket /ws" [accepted]
INFO:root:WebSocket connection accepted.
INFO:root:Starting WebSocket handler.
INFO:src.api.utils.utils:Entering handle_websocket
INFO:src.api.utils.utils:Exiting handle_websocket
INFO:     connection open
ERROR:root:Websocket error: (1001, '')
ERROR:root:WebSocket handler error: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1001, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 360, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
INFO:root:WebSocket handler finished.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1001, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 360, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 364, in handle
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 149, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 146, in app
    await func(session)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 461, in app
    await dependant.call(**solved_result.values)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 23, in websocket_endpoint
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 98, in send
    raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.
INFO:     connection closed
INFO:root:WebSocket connection request received.
INFO:     127.0.0.1:34598 - "WebSocket /ws" [accepted]
INFO:root:WebSocket connection accepted.
INFO:root:Starting WebSocket handler.
INFO:src.api.utils.utils:Entering handle_websocket
INFO:src.api.utils.utils:Exiting handle_websocket
INFO:     connection open
ERROR:root:Websocket error: (1001, '')
ERROR:root:WebSocket handler error: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1001, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 360, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
INFO:root:WebSocket handler finished.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1001, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 360, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 364, in handle
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 149, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 146, in app
    await func(session)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 461, in app
    await dependant.call(**solved_result.values)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 23, in websocket_endpoint
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 98, in send
    raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.
INFO:     connection closed
INFO:root:WebSocket connection request received.
INFO:     127.0.0.1:34600 - "WebSocket /ws" [accepted]
INFO:root:WebSocket connection accepted.
INFO:root:Starting WebSocket handler.
INFO:src.api.utils.utils:Entering handle_websocket
INFO:src.api.utils.utils:Exiting handle_websocket
INFO:     connection open
INFO:     Shutting down
ERROR:root:Websocket error: (1012, None)
ERROR:root:WebSocket handler error: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1012, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 360, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
INFO:root:WebSocket handler finished.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 25, in handle_websocket
    raw_data = await websocket.receive_text()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 120, in receive_text
    self._raise_on_disconnect(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 114, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1012, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 20, in websocket_endpoint
    await handle_websocket(websocket)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/websocket_handler.py", line 40, in handle_websocket
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 86, in send
    await self._send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 360, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/routing.py", line 364, in handle
    await self.app(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 149, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 146, in app
    await func(session)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 461, in app
    await dependant.call(**solved_result.values)
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/src/api/app.py", line 23, in websocket_endpoint
    await websocket.close()
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 181, in close
    await self.send({"type": "websocket.close", "code": code, "reason": reason or ""})
  File "/home/prasdud/playground/python/SpeechEmotion-LSTM/.venv/lib/python3.10/site-packages/starlette/websockets.py", line 98, in send
    raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.
INFO:     connection closed
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [27924]
INFO:     Stopping reloader process [27922]
